from pydantic import BaseModel, Field
from typing import Optional

class CompanyIntelligenceSchema(BaseModel):
    Company_Name: Optional[str] = Field(default=None, alias="Company Name", description="Company Name")
    Short_Name: Optional[str] = Field(default=None, alias="Short Name", description="Short Name")
    Logo: Optional[str] = Field(default=None, alias="Logo", description="Logo")
    Category: Optional[str] = Field(default=None, alias="Category", description="Category")
    Year_of_Incorporation: Optional[str] = Field(default=None, alias="Year of Incorporation", description="Year of Incorporation")
    Overview_of_the_Company: Optional[str] = Field(default=None, alias="Overview of the Company", description="Overview of the Company")
    Nature_of_Company: Optional[str] = Field(default=None, alias="Nature of Company", description="Nature of Company")
    Company_Headquarters: Optional[str] = Field(default=None, alias="Company Headquarters", description="Company Headquarters")
    Countries_Operating_In: Optional[str] = Field(default=None, alias="Countries Operating In", description="Countries Operating In")
    Number_of_Offices__beyond_HQ_: Optional[str] = Field(default=None, alias="Number of Offices (beyond HQ)", description="Number of Offices (beyond HQ)")
    Office_Locations: Optional[str] = Field(default=None, alias="Office Locations", description="Office Locations")
    Employee_Size: Optional[str] = Field(default=None, alias="Employee Size", description="Employee Size")
    Vision: Optional[str] = Field(default=None, alias="Vision", description="Vision")
    Mission: Optional[str] = Field(default=None, alias="Mission", description="Mission")
    Values: Optional[str] = Field(default=None, alias="Values", description="Values")
    Interesting_Facts: Optional[str] = Field(default=None, alias="Interesting Facts", description="Interesting Facts")
    Recent_News: Optional[str] = Field(default=None, alias="Recent News", description="Recent News")
    Website_URL: Optional[str] = Field(default=None, alias="Website URL", description="Website URL")
    LinkedIn_Profile_URL: Optional[str] = Field(default=None, alias="LinkedIn Profile URL", description="LinkedIn Profile URL")
    Twitter__X__Handle: Optional[str] = Field(default=None, alias="Twitter (X) Handle", description="Twitter (X) Handle")
    Facebook_Page_URL: Optional[str] = Field(default=None, alias="Facebook Page URL", description="Facebook Page URL")
    Instagram_Page_URL: Optional[str] = Field(default=None, alias="Instagram Page URL", description="Instagram Page URL")
    Company_Contact_Email: Optional[str] = Field(default=None, alias="Company Contact Email", description="Company Contact Email")
    Company_Phone_Number: Optional[str] = Field(default=None, alias="Company Phone Number", description="Company Phone Number")
    Regulatory___Compliance_Status: Optional[str] = Field(default=None, alias="Regulatory & Compliance Status", description="Regulatory & Compliance Status")
    Legal_Issues___Controversies: Optional[str] = Field(default=None, alias="Legal Issues / Controversies", description="Legal Issues / Controversies")
    ESG_Practices_or_Ratings: Optional[str] = Field(default=None, alias="ESG Practices or Ratings", description="ESG Practices or Ratings")
    Supply_Chain_Dependencies: Optional[str] = Field(default=None, alias="Supply Chain Dependencies", description="Supply Chain Dependencies")
    Geopolitical_Risks: Optional[str] = Field(default=None, alias="Geopolitical Risks", description="Geopolitical Risks")
    Macro_Risks: Optional[str] = Field(default=None, alias="Macro Risks", description="Macro Risks")
    Carbon_Footprint_Environmental_Impact: Optional[str] = Field(default=None, alias="Carbon Footprint/Environmental Impact", description="Carbon Footprint/Environmental Impact")
    Ethical_Sourcing_Practices: Optional[str] = Field(default=None, alias="Ethical Sourcing Practices", description="Ethical Sourcing Practices")
    Company_Introduction___Marketing_videos: Optional[str] = Field(default=None, alias="Company Introduction / Marketing videos", description="Company Introduction / Marketing videos")
    Customer_testimonial: Optional[str] = Field(default=None, alias="Customer testimonial", description="Customer testimonial")
    Quality_of_Website: Optional[str] = Field(default=None, alias="Quality of Website", description="Quality of Website")
    Website_Rating: Optional[str] = Field(default=None, alias="Website Rating", description="Website Rating")
    Website_Traffic_Rank: Optional[str] = Field(default=None, alias="Website Traffic Rank", description="Website Traffic Rank")
    Social_Media_Followers___Combined: Optional[str] = Field(default=None, alias="Social Media Followers – Combined", description="Social Media Followers – Combined")
    Glassdoor_Rating: Optional[str] = Field(default=None, alias="Glassdoor Rating", description="Glassdoor Rating")
    Indeed_Rating: Optional[str] = Field(default=None, alias="Indeed Rating", description="Indeed Rating")
    Google_Reviews_Rating: Optional[str] = Field(default=None, alias="Google Reviews Rating", description="Google Reviews Rating")
    Awards___Recognitions: Optional[str] = Field(default=None, alias="Awards & Recognitions", description="Awards & Recognitions")
    Brand_Sentiment_Score: Optional[str] = Field(default=None, alias="Brand Sentiment Score", description="Brand Sentiment Score")
    Event_Participation: Optional[str] = Field(default=None, alias="Event Participation", description="Event Participation")
    Pain_Points_Being_Addressed: Optional[str] = Field(default=None, alias="Pain Points Being Addressed", description="Pain Points Being Addressed")
    Focus_Sectors___Industries: Optional[str] = Field(default=None, alias="Focus Sectors / Industries", description="Focus Sectors / Industries")
    Services___Offerings___Products: Optional[str] = Field(default=None, alias="Services / Offerings / Products", description="Services / Offerings / Products")
    Top_Customers_by_Client_Segments: Optional[str] = Field(default=None, alias="Top Customers by Client Segments", description="Top Customers by Client Segments")
    Core_Value_Proposition: Optional[str] = Field(default=None, alias="Core Value Proposition", description="Core Value Proposition")
    Unique_Differentiators: Optional[str] = Field(default=None, alias="Unique Differentiators", description="Unique Differentiators")
    Competitive_Advantages: Optional[str] = Field(default=None, alias="Competitive Advantages", description="Competitive Advantages")
    Weaknesses___Gaps_in_Offering: Optional[str] = Field(default=None, alias="Weaknesses / Gaps in Offering", description="Weaknesses / Gaps in Offering")
    Key_Challenges_and_Unmet_Needs: Optional[str] = Field(default=None, alias="Key Challenges and Unmet Needs", description="Key Challenges and Unmet Needs")
    Key_Competitors: Optional[str] = Field(default=None, alias="Key Competitors", description="Key Competitors")
    Market_Share____: Optional[str] = Field(default=None, alias="Market Share (%)", description="Market Share (%)")
    Sales_Motion: Optional[str] = Field(default=None, alias="Sales Motion", description="Sales Motion")
    Customer_Concentration_Risk: Optional[str] = Field(default=None, alias="Customer Concentration Risk", description="Customer Concentration Risk")
    Exit_Strategy_History: Optional[str] = Field(default=None, alias="Exit Strategy/History", description="Exit Strategy/History")
    Benchmark_vs__Peers: Optional[str] = Field(default=None, alias="Benchmark vs. Peers", description="Benchmark vs. Peers")
    Future_Projections: Optional[str] = Field(default=None, alias="Future Projections", description="Future Projections")
    Strategic_Priorities: Optional[str] = Field(default=None, alias="Strategic Priorities", description="Strategic Priorities")
    Industry_Associations___Memberships: Optional[str] = Field(default=None, alias="Industry Associations / Memberships", description="Industry Associations / Memberships")
    Case_Studies___Public_Success_Stories: Optional[str] = Field(default=None, alias="Case Studies / Public Success Stories", description="Case Studies / Public Success Stories")
    Go_to_Market_Strategy: Optional[str] = Field(default=None, alias="Go-to-Market Strategy", description="Go-to-Market Strategy")
    Innovation_Roadmap: Optional[str] = Field(default=None, alias="Innovation Roadmap", description="Innovation Roadmap")
    Product_Pipeline: Optional[str] = Field(default=None, alias="Product Pipeline", description="Product Pipeline")
    Total_Addressable_Market__TAM_: Optional[str] = Field(default=None, alias="Total Addressable Market (TAM)", description="Total Addressable Market (TAM)")
    Serviceable_Addressable_Market__SAM_: Optional[str] = Field(default=None, alias="Serviceable Addressable Market (SAM)", description="Serviceable Addressable Market (SAM)")
    Serviceable_Obtainable_Market__SOM_: Optional[str] = Field(default=None, alias="Serviceable Obtainable Market (SOM)", description="Serviceable Obtainable Market (SOM)")
    Leave_policy: Optional[str] = Field(default=None, alias="Leave policy", description="Leave policy")
    Health_support: Optional[str] = Field(default=None, alias="Health support", description="Health support")
    Fixed_vs_variable_pay: Optional[str] = Field(default=None, alias="Fixed vs variable pay", description="Fixed vs variable pay")
    Bonus_predictability: Optional[str] = Field(default=None, alias="Bonus predictability", description="Bonus predictability")
    ESOPs_and_long_term_incentives: Optional[str] = Field(default=None, alias="ESOPs and long-term incentives", description="ESOPs and long-term incentives")
    Family_health_insurance: Optional[str] = Field(default=None, alias="Family health insurance", description="Family health insurance")
    Relocation_support: Optional[str] = Field(default=None, alias="Relocation support", description="Relocation support")
    Lifestyle_and_wellness_benefits: Optional[str] = Field(default=None, alias="Lifestyle and wellness benefits", description="Lifestyle and wellness benefits")
    Hiring_Velocity: Optional[str] = Field(default=None, alias="Hiring Velocity", description="Hiring Velocity")
    Employee_Turnover: Optional[str] = Field(default=None, alias="Employee Turnover", description="Employee Turnover")
    Average_Retention_Tenure: Optional[str] = Field(default=None, alias="Average Retention Tenure", description="Average Retention Tenure")
    Diversity_Metrics: Optional[str] = Field(default=None, alias="Diversity Metrics", description="Diversity Metrics")
    Work_culture: Optional[str] = Field(default=None, alias="Work culture", description="Work culture")
    Manager_quality: Optional[str] = Field(default=None, alias="Manager quality", description="Manager quality")
    Psychological_safety: Optional[str] = Field(default=None, alias="Psychological safety", description="Psychological safety")
    Feedback_culture: Optional[str] = Field(default=None, alias="Feedback culture", description="Feedback culture")
    Diversity___inclusion: Optional[str] = Field(default=None, alias="Diversity & inclusion", description="Diversity & inclusion")
    Ethical_standards: Optional[str] = Field(default=None, alias="Ethical standards", description="Ethical standards")
    Burnout_risk: Optional[str] = Field(default=None, alias="Burnout risk", description="Burnout risk")
    Layoff_history: Optional[str] = Field(default=None, alias="Layoff history", description="Layoff history")
    Mission_clarity: Optional[str] = Field(default=None, alias="Mission clarity", description="Mission clarity")
    Sustainability_and_CSR: Optional[str] = Field(default=None, alias="Sustainability and CSR", description="Sustainability and CSR")
    Crisis_behavior: Optional[str] = Field(default=None, alias="Crisis behavior", description="Crisis behavior")
    Annual_Revenues: Optional[str] = Field(default=None, alias="Annual Revenues", description="Annual Revenues")
    Annual_Profits: Optional[str] = Field(default=None, alias="Annual Profits", description="Annual Profits")
    Revenue_Mix: Optional[str] = Field(default=None, alias="Revenue Mix", description="Revenue Mix")
    Company_Valuation: Optional[str] = Field(default=None, alias="Company Valuation", description="Company Valuation")
    Year_over_Year_Growth_Rate: Optional[str] = Field(default=None, alias="Year-over-Year Growth Rate", description="Year-over-Year Growth Rate")
    Profitability_Status: Optional[str] = Field(default=None, alias="Profitability Status", description="Profitability Status")
    Key_Investors___Backers: Optional[str] = Field(default=None, alias="Key Investors / Backers", description="Key Investors / Backers")
    Recent_Funding_Rounds: Optional[str] = Field(default=None, alias="Recent Funding Rounds", description="Recent Funding Rounds")
    Total_Capital_Raised: Optional[str] = Field(default=None, alias="Total Capital Raised", description="Total Capital Raised")
    Customer_Acquisition_Cost__CAC_: Optional[str] = Field(default=None, alias="Customer Acquisition Cost (CAC)", description="Customer Acquisition Cost (CAC)")
    Customer_Lifetime_Value__CLV_: Optional[str] = Field(default=None, alias="Customer Lifetime Value (CLV)", description="Customer Lifetime Value (CLV)")
    CAC_LTV_Ratio: Optional[str] = Field(default=None, alias="CAC:LTV Ratio", description="CAC:LTV Ratio")
    Churn_Rate: Optional[str] = Field(default=None, alias="Churn Rate", description="Churn Rate")
    Net_Promoter_Score__NPS_: Optional[str] = Field(default=None, alias="Net Promoter Score (NPS)", description="Net Promoter Score (NPS)")
    Burn_Rate: Optional[str] = Field(default=None, alias="Burn Rate", description="Burn Rate")
    Runway: Optional[str] = Field(default=None, alias="Runway", description="Runway")
    Burn_Multiplier: Optional[str] = Field(default=None, alias="Burn Multiplier", description="Burn Multiplier")
    Remote_Work_Policy: Optional[str] = Field(default=None, alias="Remote Work Policy", description="Remote Work Policy")
    Typical_working_hours: Optional[str] = Field(default=None, alias="Typical working hours", description="Typical working hours")
    Overtime_expectations: Optional[str] = Field(default=None, alias="Overtime expectations", description="Overtime expectations")
    Weekend_work: Optional[str] = Field(default=None, alias="Weekend work", description="Weekend work")
    Remote___hybrid___on_site_flexibility: Optional[str] = Field(default=None, alias="Remote / hybrid / on-site flexibility", description="Remote / hybrid / on-site flexibility")
    Central_vs_peripheral_location: Optional[str] = Field(default=None, alias="Central vs peripheral location", description="Central vs peripheral location")
    Public_transport_access: Optional[str] = Field(default=None, alias="Public transport access", description="Public transport access")
    Cab_availability_and_company_cab_policy: Optional[str] = Field(default=None, alias="Cab availability and company cab policy", description="Cab availability and company cab policy")
    Commute_time_from_airport: Optional[str] = Field(default=None, alias="Commute time from airport", description="Commute time from airport")
    Office_zone_type: Optional[str] = Field(default=None, alias="Office zone type", description="Office zone type")
    Area_safety: Optional[str] = Field(default=None, alias="Area safety", description="Area safety")
    Company_safety_policies: Optional[str] = Field(default=None, alias="Company safety policies", description="Company safety policies")
    Office_infrastructure_safety: Optional[str] = Field(default=None, alias="Office infrastructure safety", description="Office infrastructure safety")
    Emergency_response_preparedness: Optional[str] = Field(default=None, alias="Emergency response preparedness", description="Emergency response preparedness")
    CEO_Name: Optional[str] = Field(default=None, alias="CEO Name", description="CEO Name")
    CEO_LinkedIn_URL: Optional[str] = Field(default=None, alias="CEO LinkedIn URL", description="CEO LinkedIn URL")
    Key_Business_Leaders: Optional[str] = Field(default=None, alias="Key Business Leaders", description="Key Business Leaders")
    Warm_Introduction_Pathways: Optional[str] = Field(default=None, alias="Warm Introduction Pathways", description="Warm Introduction Pathways")
    Decision_Maker_Accessibility: Optional[str] = Field(default=None, alias="Decision Maker Accessibility", description="Decision Maker Accessibility")
    Primary_Contact_Person_s_Name: Optional[str] = Field(default=None, alias="Primary Contact Person's Name", description="Primary Contact Person's Name")
    Primary_Contact_Person_s_Title: Optional[str] = Field(default=None, alias="Primary Contact Person's Title", description="Primary Contact Person's Title")
    Primary_Contact_Person_s_Email: Optional[str] = Field(default=None, alias="Primary Contact Person's Email", description="Primary Contact Person's Email")
    Primary_Contact_Person_s_Phone_Number: Optional[str] = Field(default=None, alias="Primary Contact Person's Phone Number", description="Primary Contact Person's Phone Number")
    Board_of_Directors___Advisors: Optional[str] = Field(default=None, alias="Board of Directors / Advisors", description="Board of Directors / Advisors")
    Training_Development_Spend: Optional[str] = Field(default=None, alias="Training/Development Spend", description="Training/Development Spend")
    Onboarding_and_training_quality: Optional[str] = Field(default=None, alias="Onboarding and training quality", description="Onboarding and training quality")
    Learning_culture: Optional[str] = Field(default=None, alias="Learning culture", description="Learning culture")
    Exposure_quality: Optional[str] = Field(default=None, alias="Exposure quality", description="Exposure quality")
    Mentorship_availability: Optional[str] = Field(default=None, alias="Mentorship availability", description="Mentorship availability")
    Internal_mobility: Optional[str] = Field(default=None, alias="Internal mobility", description="Internal mobility")
    Promotion_clarity: Optional[str] = Field(default=None, alias="Promotion clarity", description="Promotion clarity")
    Tools_and_technology_access: Optional[str] = Field(default=None, alias="Tools and technology access", description="Tools and technology access")
    Role_clarity: Optional[str] = Field(default=None, alias="Role clarity", description="Role clarity")
    Early_ownership: Optional[str] = Field(default=None, alias="Early ownership", description="Early ownership")
    Work_impact: Optional[str] = Field(default=None, alias="Work impact", description="Work impact")
    Execution_vs_thinking_balance: Optional[str] = Field(default=None, alias="Execution vs thinking balance", description="Execution vs thinking balance")
    Automation_level: Optional[str] = Field(default=None, alias="Automation level", description="Automation level")
    Cross_functional_exposure: Optional[str] = Field(default=None, alias="Cross-functional exposure", description="Cross-functional exposure")
    Company_maturity: Optional[str] = Field(default=None, alias="Company maturity", description="Company maturity")
    Brand_value: Optional[str] = Field(default=None, alias="Brand value", description="Brand value")
    Client_quality: Optional[str] = Field(default=None, alias="Client quality", description="Client quality")
    Exit_opportunities: Optional[str] = Field(default=None, alias="Exit opportunities", description="Exit opportunities")
    Skill_relevance: Optional[str] = Field(default=None, alias="Skill relevance", description="Skill relevance")
    External_recognition: Optional[str] = Field(default=None, alias="External recognition", description="External recognition")
    Network_strength: Optional[str] = Field(default=None, alias="Network strength", description="Network strength")
    Global_exposure: Optional[str] = Field(default=None, alias="Global exposure", description="Global exposure")
    Technology_Partners: Optional[str] = Field(default=None, alias="Technology Partners", description="Technology Partners")
    Intellectual_Property: Optional[str] = Field(default=None, alias="Intellectual Property", description="Intellectual Property")
    R_D_Investment: Optional[str] = Field(default=None, alias="R&D Investment", description="R&D Investment")
    AI_ML_Adoption_Level: Optional[str] = Field(default=None, alias="AI/ML Adoption Level", description="AI/ML Adoption Level")
    Tech_Stack_Tools_Used: Optional[str] = Field(default=None, alias="Tech Stack/Tools Used", description="Tech Stack/Tools Used")
    Cybersecurity_Posture: Optional[str] = Field(default=None, alias="Cybersecurity Posture", description="Cybersecurity Posture")
    Partnership_Ecosystem: Optional[str] = Field(default=None, alias="Partnership Ecosystem", description="Partnership Ecosystem")
    Industry_Benchmark_Technology_Adoption_Rating: Optional[str] = Field(default=None, alias="Industry Benchmark Technology Adoption Rating", description="Industry Benchmark Technology Adoption Rating")
