import {
  Activity,
  BadgeDollarSign,
  BarChart3,
  Briefcase,
  Building2,
  Cpu,
  Crown,
  Gauge,
  Globe2,
  HeartHandshake,
  Landmark,
  Network,
  ShieldCheck,
  Sparkles,
  Users,
} from "lucide-react";


export const NAV_ITEMS = [
  { label: "Home", path: "/" },
  { label: "Explore Companies", path: "/explore" },
  { label: "Categories", path: "/categories" },
  { label: "Compare", path: "/compare" },
  { label: "Skill Mapping", path: "/skill-mapping" },
  { label: "Analytics", path: "/analytics" },
  { label: "Faculty Boards", path: "/faculty/review-boards" },
  { label: "Research Engine", path: "/research" },
];

export const VISUALS = {
  hero: "https://static.prod-images.emergentagent.com/jobs/edd86608-501a-4efe-94f1-869bc5bdae3c/images/77f43fe808e7a2ebcf127ed7f180548b90795fb0624c6ad95ec7d74a97f19bc5.png",
  office: "https://images.pexels.com/photos/34746047/pexels-photo-34746047.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  data: "https://images.unsplash.com/photo-1765046255479-669cf07a0230?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzNDR8MHwxfHNlYXJjaHwyfHxhYnN0cmFjdCUyMHRlY2hub2xvZ3klMjBkYXRhJTIwdmlzdWFsaXphdGlvbnxlbnwwfHx8fDE3NzY2MDg4NzZ8MA&ixlib=rb-4.1.0&q=85",
  technology: "https://static.prod-images.emergentagent.com/jobs/edd86608-501a-4efe-94f1-869bc5bdae3c/images/42a9d539f832d915ddac5a27d2356048564f6d224f5e5e9c9a3136d36c1bb5ae.png",
};

export const HOME_INSIGHT_FIELDS = [
  { label: "Hiring velocity", key: "hiring_velocity_distribution" },
  { label: "Profitability mix", key: "profitability_mix" },
  { label: "Work mode distribution", key: "work_mode_distribution" },
];

export const COMPARISON_SECTIONS = [
  {
    title: "Culture",
    fields: ["Work culture", "Manager quality", "Psychological safety", "Burnout risk"],
  },
  {
    title: "Compensation",
    fields: ["Fixed vs variable pay", "Bonus predictability", "ESOPs and long-term incentives", "Lifestyle and wellness benefits"],
  },
  {
    title: "Learning",
    fields: ["Learning culture", "Mentorship availability", "Internal mobility", "Skill relevance"],
  },
  {
    title: "Financials",
    fields: ["Annual Revenues", "Annual Profits", "Profitability Status", "Company Valuation"],
  },
  {
    title: "Technology",
    fields: ["AI/ML Adoption Level", "Tech Stack/Tools Used", "Automation level", "Cybersecurity Posture"],
  },
];

export const COMPANY_FRAME_SECTIONS = [
  {
    id: "overview",
    title: "Company Overview",
    icon: Building2,
    image: VISUALS.office,
    fields: [
      "Company Name",
      "Short Name",
      "Logo",
      "Category",
      "Year of Incorporation",
      "Nature of Company",
      "Company Headquarters",
      "Countries Operating In",
      "Number of Offices (beyond HQ)",
      "Office Locations",
      "Employee Size",
      "Overview of the Company",
      "Vision",
      "Mission",
      "Values",
      "Interesting Facts",
      "Recent News",
    ],
  },
  {
    id: "business-market",
    title: "Business & Market",
    icon: Briefcase,
    image: VISUALS.hero,
    fields: [
      "Pain Points Being Addressed",
      "Focus Sectors / Industries",
      "Services / Offerings / Products",
      "Top Customers by Client Segments",
      "Core Value Proposition",
      "Unique Differentiators",
      "Competitive Advantages",
      "Weaknesses / Gaps in Offering",
      "Key Challenges and Unmet Needs",
      "Key Competitors",
      "Market Share (%)",
      "Sales Motion",
      "Customer Concentration Risk",
      "Exit Strategy/History",
      "Benchmark vs. Peers",
      "Future Projections",
      "Strategic Priorities",
      "Industry Associations / Memberships",
      "Case Studies / Public Success Stories",
      "Go-to-Market Strategy",
      "Innovation Roadmap",
      "Product Pipeline",
      "Total Addressable Market (TAM)",
      "Serviceable Addressable Market (SAM)",
      "Serviceable Obtainable Market (SOM)",
    ],
  },
  {
    id: "culture-people",
    title: "Culture & People",
    icon: Users,
    image: VISUALS.office,
    fields: [
      "Hiring Velocity",
      "Employee Turnover",
      "Average Retention Tenure",
      "Diversity Metrics",
      "Work culture",
      "Manager quality",
      "Psychological safety",
      "Feedback culture",
      "Diversity & inclusion",
      "Ethical standards",
      "Burnout risk",
      "Layoff history",
      "Mission clarity",
      "Sustainability and CSR",
      "Crisis behavior",
    ],
  },
  {
    id: "learning-growth",
    title: "Learning & Growth",
    icon: Sparkles,
    image: VISUALS.data,
    fields: [
      "Training/Development Spend",
      "Onboarding and training quality",
      "Learning culture",
      "Exposure quality",
      "Mentorship availability",
      "Internal mobility",
      "Promotion clarity",
      "Tools and technology access",
      "Role clarity",
      "Early ownership",
      "Work impact",
      "Execution vs thinking balance",
      "Cross-functional exposure",
      "Company maturity",
      "Exit opportunities",
      "Skill relevance",
      "External recognition",
      "Network strength",
      "Global exposure",
    ],
  },
  {
    id: "compensation",
    title: "Compensation",
    icon: BadgeDollarSign,
    image: VISUALS.hero,
    fields: [
      "Leave policy",
      "Health support",
      "Fixed vs variable pay",
      "Bonus predictability",
      "ESOPs and long-term incentives",
      "Family health insurance",
      "Relocation support",
      "Lifestyle and wellness benefits",
    ],
  },
  {
    id: "work-logistics",
    title: "Work Logistics",
    icon: Globe2,
    image: VISUALS.office,
    fields: [
      "Remote Work Policy",
      "Typical working hours",
      "Overtime expectations",
      "Weekend work",
      "Remote / hybrid / on-site flexibility",
      "Central vs peripheral location",
      "Public transport access",
      "Cab availability and company cab policy",
      "Commute time from airport",
      "Office zone type",
      "Area safety",
      "Company safety policies",
      "Office infrastructure safety",
      "Emergency response preparedness",
    ],
  },
  {
    id: "financials",
    title: "Financials",
    icon: Landmark,
    image: VISUALS.data,
    fields: [
      "Annual Revenues",
      "Annual Profits",
      "Revenue Mix",
      "Company Valuation",
      "Year-over-Year Growth Rate",
      "Profitability Status",
      "Key Investors / Backers",
      "Recent Funding Rounds",
      "Total Capital Raised",
      "Customer Acquisition Cost (CAC)",
      "Customer Lifetime Value (CLV)",
      "CAC:LTV Ratio",
      "Churn Rate",
      "Net Promoter Score (NPS)",
      "Burn Rate",
      "Runway",
      "Burn Multiplier",
    ],
  },
  {
    id: "technology",
    title: "Technology",
    icon: Cpu,
    image: VISUALS.technology,
    fields: [
      "Technology Partners",
      "Intellectual Property",
      "R&D Investment",
      "AI/ML Adoption Level",
      "Tech Stack/Tools Used",
      "Cybersecurity Posture",
      "Partnership Ecosystem",
      "Industry Benchmark Technology Adoption Rating",
      "Automation level",
    ],
  },
  {
    id: "leadership",
    title: "Leadership",
    icon: Crown,
    image: VISUALS.office,
    fields: [
      "CEO Name",
      "CEO LinkedIn URL",
      "Key Business Leaders",
      "Warm Introduction Pathways",
      "Decision Maker Accessibility",
      "Primary Contact Person's Name",
      "Primary Contact Person's Title",
      "Primary Contact Person's Email",
      "Primary Contact Person's Phone Number",
      "Board of Directors / Advisors",
    ],
  },
  {
    id: "brand-digital",
    title: "Brand & Digital",
    icon: Network,
    image: VISUALS.data,
    fields: [
      "Website URL",
      "LinkedIn Profile URL",
      "Twitter (X) Handle",
      "Facebook Page URL",
      "Instagram Page URL",
      "Company Contact Email",
      "Company Phone Number",
      "Regulatory & Compliance Status",
      "Legal Issues / Controversies",
      "ESG Practices or Ratings",
      "Supply Chain Dependencies",
      "Geopolitical Risks",
      "Macro Risks",
      "Carbon Footprint/Environmental Impact",
      "Ethical Sourcing Practices",
      "Company Introduction / Marketing videos",
      "Customer testimonial",
      "Quality of Website",
      "Website Rating",
      "Website Traffic Rank",
      "Social Media Followers – Combined",
      "Glassdoor Rating",
      "Indeed Rating",
      "Google Reviews Rating",
      "Awards & Recognitions",
      "Brand Sentiment Score",
      "Event Participation",
      "Brand value",
      "Client quality",
    ],
  },
  {
    id: "hiring-roles",
    title: "Hiring Intelligence",
    icon: Sparkles,
    image: VISUALS.technology,
    fields: [
      "Job Roles (InnovX Master)",
      "Hiring Rounds",
      "Typical Assessment Questions",
      "Compensation & Benefits",
      "Skill Fit Predictors",
    ],
  },
];

export const ANALYTICS_SECTIONS = [
  { title: "Category distribution", key: "category_distribution", icon: ShieldCheck },
  { title: "Hiring velocity", key: "hiring_velocity_distribution", icon: Gauge },
  { title: "Profitability mix", key: "profitability_mix", icon: Activity },
  { title: "Work mode distribution", key: "work_mode_distribution", icon: BarChart3 },
];